# Generated by Django 3.2.16 on 2022-12-03 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_customerinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='paystack_payment_intent',
            new_name='stripe_payment_intent',
        ),
    ]
